# Generated by Django 5.0.6 on 2024-07-13 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_description_publisher_country_alter_member_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.CharField(choices=[('Purchased', 'Purchased'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Purchased', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(related_name='orders', to='myapp.book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='myapp.member'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(choices=[(1, 'Type 1'), (2, 'Type 2')]),
        ),
    ]
